<?php
$template_image_rating = '<tr>
                <td colspan="6" class="tableh2_compact"><strong>'.RATE_THIS_PIC.'</strong> {VOTES}</td>
        </tr>
        <tr>
                <td class="tableb_compact" width="17%" align="center"><a href="{RATE0}" title="'.RUBBISH.'"><img src="'.$CPG_M_DIR.'/images/rating0.gif" alt="'.RUBBISH.'" border="0"><br /></a></td>
                <td class="tableb_compact" width="17%" align="center"><a href="{RATE1}" title="'.POOR.'"><img src="'.$CPG_M_DIR.'/images/rating1.gif" alt="'.POOR.'" border="0"><br /></a></td>
                <td class="tableb_compact" width="17%" align="center"><a href="{RATE2}" title="'.FAIR.'"><img src="'.$CPG_M_DIR.'/images/rating2.gif" alt="'.FAIR.'" border="0"><br /></a></td>
                <td class="tableb_compact" width="17%" align="center"><a href="{RATE3}" title="'.GOOD.'"><img src="'.$CPG_M_DIR.'/images/rating3.gif" alt="'.GOOD.'" border="0"><br /></a></td>
                <td class="tableb_compact" width="17%" align="center"><a href="{RATE4}" title="'.EXCELLENT.'"><img src="'.$CPG_M_DIR.'/images/rating4.gif" alt="'.EXCELLENT.'" border="0"><br /></a></td>
                <td class="tableb_compact" width="17%" align="center"><a href="{RATE5}" title="'.GREAT.'"><img src="'.$CPG_M_DIR.'/images/rating5.gif" alt="'.GREAT.'" border="0"><br /></a></td>
        </tr>';
?>
