<?php
define("_ADDVID","Add Video");
define("_TITLE","Title");
define("_POSTEDON","Posted on");
define("_POSTEDBY","Posted by");
define("_VVIEW","View");
define("_VIEWS","Views");
define("_PREVIOUS","Previous Page");
define("_NEXT","Next Page");
define("_DESCRIPTION","Description");
define("_VIDURL","Video URL");
define("_PPURL","Picture Preview URL");
define("_WIDTH","Width");
define("_HEIGHT","Height");
define("_PLUGIN","Plugin");
define("_WINDOWSMP","Windows Media Player");
define("_FLASHP","Flash Player");
define("_QUICKTIMEP","Quicktime Player");
define("_REALP","Real Player");
define("_REQUIRED","Required Fields");
define("_VIDADDPUBLICNOTE","Your video has been submitted successfully and an admin will check it before the video will be able to be viewed by the public.");
define("_VIDADDPUBLICNOTE2","Your video has been submitted successfully added to our collection.");
define("_BROKENNOTICE","Thank you for reporting this video as not working. The admin has been notified.");
define("_BACK","back");
define("_VIDEOCOLECTION","Video Collection");
define("_REPORTP1","You are about to report");
define("_REPORTP2","as not working. Please leave your username and email below and the admin will be notified. Thank You!");
define("_USERNAME","Username");
define("_EMAIL","Email");
define("_SUBMIT","Submit");
define("_TYCOMMENT","Thank you for your comment");
define("_TYRATE","Thank you for your rating");
define("_SENDTOAFRIEND","Send to a friend");
define("_BROKEN","Broken");
define("_SUBMITAVID","Submit Video");
define("_RATING","Rating");
define("_TVOTES","Total Votes");
define("_PAGE","Page");
define("_NOVIDSINDB","No videos have been entered into the Database yet");
define("_DOWNLOADFLASH","Are you having trouble veiwing this flash file? Download it");
define("_HERE","here");
define("_NOCOMMENTS","No comments for this video");
define("_NONE","None");
define("_CATEGORY","Category");
define("_REGBROKEN","Only registered members are allowed to report videos as broken");
define("_REGCOMMENT","Only registered members are allowed to comment");
define("_REGSUBMIT","Only registered members are allowed to submit videos");
define("_REGRATE","Only registered members are allowed to rate videos");
define("_REGSEND","Only registered members are allowed to send videos to a friend");
define("_REGWATCH","Only registered members are allowed to watch videos");
define("_VIDEOCOLECTION","Video Collection");
define("_YOURFRIEND","Your friend");
define("_HASRECOMMEND","has recommended that you see this video");
define("_EMAILSENT","Email sent to");
define("_EMAILNOTSENT","There was an error sending your email");
define("_YNAME","Your Name");
define("_YEMAIL","Your Email");
define("_FNAME","Friend's Name");
define("_FEMAIL","Friend's Email");
define("_SEND","Send");
// NEW TO V4.1
define("_SORT","Sort");
define("_SEARCH","Search");
define("_SEARCHVIDS","Search Videos");
define("_SORTANDSEARCH","Sort & Search Videos");
define("_ORDERVIDS","Order Videos By");
define("_DISPLAYCATEGORY","Display By Category");
define("_ALL","All");
define("_NEWEST","Newest");
define("_OLDEST","Oldest");
define("_HIGHESTR","Highest Rated");
define("_MOSTVIEW","Most Viewed");
define("_EMBEDVIDURL","Video URL or &lt;embed&gt; code");
define("_CUSTOMEMBED","Custom &lt;embed&gt; Code");
define("_NOMATCHES","Sorry no search results were found");
// NEW to V4.2
define("_VS_COMMENT","Comment"); // DLETE define("_COMMENT","Comment"); above
define("_VS_COMMENTS","Comments"); // DLETE define("_COMMENTS","Comments"); above
define("_NOTALLFIELDSFILLED","Not all required fields were filled in, please go back and try again");
define("_NOTALLFIELDSFILLEDCORRECTLY","Not all fields were filled in correctly, please go back and try again");
define("_PICTURETHUMB","Picture Thumbnail");
define("_NOCOMMENTENT","No comment entered");
define("_COMMENTMODED","The comment has been modified");
define("_ERROR","Error");
define("_JOINON","Joined on");
define("_BACKTOTOP","Back to top");
define("_SENDPMESS","Send private message");
define("_VISITPOSTWEB","Visit poster's website");
define("_SENDEMAIL","Send e-mail");
define("_AIMADDRESS","AIM Address");
define("_YIMADDRESS","YIM Address");
define("_MSNMESSENGERADD","MSN Messenger");
define("_ICQNUMBER","ICQ Number");
define("_AREUSURE","Are you sure?");
define("_EDITCOMM","Edit Comment");
define("_DELETECOMM","Delete Comment");
define("_BACKTOVIDS","Back to Videos");
define("_STATISTICS","Statistics");
define("_WECURRENTHAVE","We currently have");
define("_VS_VIDEOS","Videos");
define("_WITHALLVIDSHAD","With all these videos we have had");
define("_VS_VIEWS","views");
define("_ONAVERAGE","On average thats");
define("_VIEWSPERVID","views per video");
define("_COMMSPERVID","comments per video");
define("_INTOTALHAVE","In total we have");
define("_VS_COMMS","comments");
define("_ALLTOGETHERHAD","All together we have had");
define("_VS_RATES","rates");
define("_AVERAGERATEPV","The average rate per video is");
define("_MOREFROMUSER","More from this user");
define("_PLAYINPOPUP","Play Video in Popup");
define("_MOREVIDS","More Videos");
define("_HELPFORSEARCH","Search methods:<br>title:string (Searches videos by title)<br>description:string (Searches videos by description)<br>user:string (Searches videos by user)");
define("_VS_INFO", "Info");
define("_REPORTASBROKEN", "Report this video as broken");
define("_RATINGSANDREVIEWS", "Ratings and Reviews");
define("_RATE", "Rate"); // DELETE define("_RATEVID","Rate this video"); above
define("_ADDCOMMENTTOVID", "Add a comment to this video");
define("_TELLEVERYBOUTVID", "Tell everyone about this video");
define("_HTMLLINK", "HTML Link");
define("_BBLINK", "BB Link");
define("_EMAILLINK", "Email Link");
define("_DOWNLOAD", "Download");
define("_DOWNLOADVID", "Download Video"); // DELETE define("_DOWNLOADVID","Are you having trouble veiwing this video? Download it"); above
// NEW to 4.5
define("_VS_ACCEPT", "Accept");
define("_VS_REJECT", "Reject");
define("_YOUTUBEVP", "YouTube Player");
define("_GOOGLEVP", "Google Video Player");
define("_ALPHABETICALLY", "Alphabetically");
define("_EMBEDEDHTML", "Embeded HTML");
define("_WINAMP", "Winamp");
define("_FLVPLAYER", "FLV Player");
?>