<?php
/***************************************************************************
      This file was automatically generated by Admin FAQ Editor
 ***************************************************************************/
/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
/************************************************************************/
/* Platinum Nuke Pro: Expect to be impressed                  COPYRIGHT */
/*                                                                      */
/* Copyright (c) 2004 - 2006 by http://www.techgfx.com                  */
/*     Techgfx - Graeme Allan                       (goose@techgfx.com) */
/*                                                                      */
/* Copyright (c) 2004 - 2006 by http://www.nukeplanet.com               */
/*     Loki / Teknerd - Scott Partee           (loki@nukeplanet.com)    */
/*                                                                      */
/* Copyright (c) 2007 - 2017 by http://www.platinumnukepro.com          */
/*                                                                      */
/* Refer to platinumnukepro.com for detailed information on this CMS    */
/*******************************************************************************/
/* This file is part of the PlatinumNukePro CMS - http://platinumnukepro.com   */
/*                                                                             */
/* This program is free software; you can redistribute it and/or               */
/* modify it under the terms of the GNU General Public License                 */
/* as published by the Free Software Foundation; either version 2              */
/* of the License, or any later version.                                       */
/*                                                                             */
/* This program is distributed in the hope that it will be useful,             */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of              */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               */
/* GNU General Public License for more details.                                */
/*                                                                             */
/* You should have received a copy of the GNU General Public License           */
/* along with this program; if not, write to the Free Software                 */
/* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. */
/*******************************************************************************/
// 
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//
$faq[] = array("--", "Posting");
$faq[] = array("Please read the following guidelines for Forum posting", "[b]1.[/b] Before posting, search the forums. Be specific in your searches.
<br /> 
<br />[b]2.[/b] When posting, [b]DO NOT[/b] give your topic a title of:
<br />[list]
<br />[*] HELP ME PLEASE! 
<br />[*] I NEED HELP! 
<br />[*] I have a question. 
<br />[*] BIG problem! 
<br />[*] NOOB needs help! 
<br />[*] Problems 
<br />[*] URGENT! 
<br />[*] HELP ME PLEASE.[/list]
<br />[b]or ANYTHING like the above!!! 
<br />[/b]
<br />
<br />[b]BE SPECIFIC[/b] in choosing a title for your post. It can help us better help you. 
<br />[b]If you use a title that is generalized and not specific, it MAY be removed altogether[/b] 
<br />
<br />[b]3.[/b] Help us help you. When you post, post as much information as you can. 
<br />[list]
<br />[*] Setup 
<br />[*] Versions of software 
<br />[*] Specific problem 
<br />[*] Be as detailed as possible 
<br />[/list]
<br />
<br />[b]4.[/b] Posting a topic 3 or 4 or 5 times will not get you a quicker response...it will more than likely get No response.
<br /> 
<br />[b]5.[/b] Please try to only start New topics as necessary. If a similar topic exists, please post in it. It will move that topic to the top of the list and your post will be seen. It also is a good idea since there may be a few users subscribed to that posts notification. 
<br />
<br />[b]6.[/b] Post your topic in the respective forum. 
<br />i.e. Requests go in the Requests forum, Off topic stuff goes in the Off topic forum. 
<br />Neglecting to do so will get your topic moved or even removed! 
<br />
<br />[b]7.[/b] [b]DO NOT[/b] contact the administrators and moderators by Email or Private Messaging with questions [b]UNLESS[/b] they have told you to do so! Uninvited private messages and privately addressed questions will be [b]IGNORED![/b] 
<br />
<br />We try to help as much as we can. Time is not free and any help we give is purely voluntary. ");
$faq[] = array("What language can I post in?", "The main language that is used on the site is English, and we would like to keep it that way. Also we have a French chit chat Forum but that can't be used too often because only one member speaks that language. So please stick with English, how hard it sometimes can be.");
$faq[] = array("How to request or submit a bug report? ", "[i]Requests:[/i] <br />Give the name of the mod <br />Give the link to the original mod (where we can download it). <br />Give a short description of the use of the mod <br /><br />[i]Bugs:[/i] <br />Post the line that gives you an error message. <br />Make sure you have put debug on. <br />Place a link to your site (pref where you got the error). ");
$faq[] = array("--", "Other Rules");
$faq[] = array("Spamming", "Please do not spam our forums. Our Moderators will ban users that spam!");
$faq[] = array("User Name", "Please use a \"correct\" username! Any usernames that are insulting or in any way have something to with diseases or cursing will be banned! ");
$faq[] = array("Contacting the Administrators, moderators.", "Please do not contact the administrators or moderators by:<br />- [b]Email[/b]<br />- [b]MSN,AIM, Yahoo Messenger, ICQ[/b]<br />- [b]Private Message[/b]<br /><br />You can [b]only[/b] contact an administrator or moderator if they have said so. Please obey this because every pm/email/etc will be ignored in the future. <br /><br />");
$faq[] = array("What is bump?", "If you have requested/posted a Bug Report a time ago and still have had no response too it, please use a bump, instead of: <br /><br />PLEASE HELP ME! (example). <br /><br />By some time i mean more than 2 or 3 days, you will get [b]ONE[/b] warning if you abuse this. If you bump again, or spam another time [b]YOU WILL BE BANNED![/b] <br /><br />Please understand, [b]WE[/b] also have private lives and therefor we are not always able to respond right away! ");
$faq[] = array("Spamming Via Private Message System", "Sending avertisement throughout the Private Message System, is not allowed. We do monitor the Private Message too see if this rule is followed. If we catch anybody sending advertisements too our members, or if it gets reported, your ip gets banned without further notice, and forever. [b]NO WARNING WILL BE GIVEN[/b] and you will be banned, also you hosting provider will be contacted! [b]YOU HAVE BEEN WARNED[/b]");
?>
