<SCRIPT>

function makemymod(){
	var input = document.modumake.input.value;
	output = "echo\"";
	for (var c = 0; c < input.length; c++){
		if ((input.charAt(c) == "\n" || input.charAt(c) == "\r")){
			output += "\"";
			if (c != input.length - 1) output +="\n  . \"";
			c++;
			}
		else {
			if (input.charAt(c) == "\"") {
				output += "\\\"";
				}
			else {
				if (input.charAt(c) == "\\"){
					output += "\\\\";
					}
				else {
					output += input.charAt(c);
					if (c == input.length -1) output += "\"";	
					}
				}
			}
		
		}

info="<\?php\n" + 
"/****************************************************************************/\n" +
"/*  Generated by Module Creator - By Disipal Designs (www.disipal.net)      */\n" +
"/*  PHP-Nuke Tools v4.00                                                    */\n" +
"/****************************************************************************/\n" +
"if (!defined('MODULE_FILE')) {\n" + 
"   die (\"You can't access this file directly...\");\n" + 
"}\n" +

"require_once(\"mainfile.php\");\n" +
"$module_name = basename(dirname(__FILE__));\n" +
"get_lang($module_name);\n" +
"include_once(\"header.php\");\n" +
"define('INDEX_FILE', true);\n" +
"OpenTable();\n"


info2=";\n" +
"CloseTable();\n" +
"include_once(\"footer.php\");\n" +
"\n?>";

	document.modumake.output.value =info+output+info2;
}

</SCRIPT>