<SCRIPT LANGUAGE="JavaScript">


<!-- Begin
function create(form) {
  if (confirm("Are you sure?")) {
   form.story.value = "Generated by Meta Tag Creator \n" +
   "PHP-Nuke Tools\n" +
   "By Disipal site  \n" +
   " http://www.disipal.net\n\n";
    if (form.input1.value != "") {
      form.story.value +="<META NAME=\"Title\" CONTENT=\"" +
      form.input1.value + "\">\n";
    }
    if (form.input2.value != "") {
      form.story.value +="<META NAME=\"Author\" CONTENT=\"" +
      form.input2.value + "\">\n";
    }
    if (form.input3.value != "") {
      form.story.value +="<META NAME=\"Subject\" CONTENT=\"" +
      form.input3.value + "\">\n";
    }
    if (form.input4.value != "") {
      form.story.value +="<META NAME=\"Description\" CONTENT=\"" +
      form.input4.value + "\">\n";
    }
    if (form.input5.value != "") {
      form.story.value +="<META NAME=\"Keywords\" CONTENT=\"" +
      form.input5.value + "\">\n";
    }
    if (form.input6.value != "") {
      form.story.value +="<META NAME=\"Generator\" CONTENT=\"" +
      form.input6.value + "\">\n";
    }
    if (form.input7.value != "") {
      form.story.value +="<META NAME=\"Language\" CONTENT=\"" +
      form.input7.value + "\">\n";
    }
    if (form.input8.value != "") {
      form.story.value +="<META NAME=\"Expires\" CONTENT=\"" +
      form.input8.value + "\">\n";
    }
    if (form.input9.value != "") {
      form.story.value +="<META NAME=\"Abstract\" CONTENT=\"" +
      form.input9.value + "\">\n";
    }
    if (form.input10.value != "") {
      form.story.value +="<META NAME=\"Copyright\" CONTENT=\"© " +
      form.input10.value + "\">\n";
    }
    if (form.input11.value != "") {
      form.story.value +="<META NAME=\"Designer\" CONTENT=\"" +
      form.input11.value + "\">\n";
    }
    if (form.input12.value != "") {
      form.story.value +="<META NAME=\"Publisher\" CONTENT=\"" +
      form.input12.value + "\">\n";
    }
    if (form.input13.value != "") {
      form.story.value +="<META NAME=\"Revisit-After\" CONTENT=\"" +
      form.input13.value + " \Days\">\n";
    }
    if (form.input14.value != "") {
      form.story.value +="<META NAME=\"Distribution\" CONTENT=\"" +
      form.input14.options[form.input14.selectedIndex].value + "\">\n";
    }
    if (form.input15.value != "") {
      form.story.value +="<META NAME=\"Robots\" CONTENT=\"" +
      form.input15.options[form.input15.selectedIndex].value + "\">\n";
    }
  }
}
//  End -->
</script>