
start = "<"
slash = "/"
fnctn = "func"
nmos = " onMouse"
open_c = "("
open_cc = "{"


document.write("<CENTER>\n")
document.write("\n")
document.write("",start,"scr","ipt language = ",'"',"javascr","ipt",'"',">\n")
document.write("",start,"!--\n")
document.write("\n")
document.write("",fnctn,"tion launchhex",open_c,")",open_cc,"\n")
document.write("y=window.open",open_c,"",'"',"http:",slash,"",slash,"www.disipal.net",slash,"colorhex.htm",'"',",",'"',"Hex",'"',",",'"',"width=310,height=410,top=100,left=100,resizeable=no,scrollbars=no,menubar=no,toolbar=no,status=yes",'"',")}\n")
document.write("\n")
document.write("",slash,"",slash,"-->\n")
document.write("",start,"",slash,"scr","ipt>\n")
document.write("",start,"scr","ipt language = ",'"',"javascr","ipt",'"',">\n")
document.write("",start,"!--\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("",fnctn,"tion generate",open_c,")",open_cc,"\n")
document.write("csscontentpart = ",'"',"",'"',"\n")
document.write("\n")
document.write("facecolor = ",'"',"",'"',"\n")
document.write("\n")
document.write("highlightcolor = ",'"',"",'"',"\n")
document.write("tdlightcolor = ",'"',"",'"',"\n")
document.write("\n")
document.write("darkshadowcolor = ",'"',"",'"',"\n")
document.write("shadowcolor = ",'"',"",'"',"\n")
document.write("\n")
document.write("arrowcolor = ",'"',"",'"',"\n")
document.write("trackcolor = ",'"',"",'"',"\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("if",open_c,"document.barspecs.face.value != ",'"',"",'"',")",open_cc,"facecolor = document.barspecs.face.value}\n")
document.write("if",open_c,"document.barspecs.highlight.value != ",'"',"",'"',")",open_cc,"highlightcolor = document.barspecs.highlight.value}\n")
document.write("if",open_c,"document.barspecs.tdlight.value != ",'"',"",'"',")",open_cc,"tdlightcolor = document.barspecs.tdlight.value}\n")
document.write("if",open_c,"document.barspecs.darkshadow.value != ",'"',"",'"',")",open_cc,"darkshadowcolor = document.barspecs.darkshadow.value}\n")
document.write("if",open_c,"document.barspecs.shadow.value != ",'"',"",'"',")",open_cc,"shadowcolor = document.barspecs.shadow.value}\n")
document.write("if",open_c,"document.barspecs.arrow.value != ",'"',"",'"',")",open_cc,"arrowcolor = document.barspecs.arrow.value}\n")
document.write("if",open_c,"document.barspecs.track.value != ",'"',"",'"',")",open_cc,"trackcolor = document.barspecs.track.value}\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("if",open_c,"facecolor != ",'"',"",'"',")",open_cc,"csscontentpart += ",'"',"scrollbar-face-color: ",'"'," + facecolor + ",'"',";\\n",'"',"}\n")
document.write("if",open_c,"highlightcolor != ",'"',"",'"',")",open_cc,"csscontentpart += ",'"',"scrollbar-highlight-color: ",'"'," + highlightcolor + ",'"',";\\n",'"',"}\n")
document.write("if",open_c,"tdlightcolor != ",'"',"",'"',")",open_cc,"csscontentpart += ",'"',"scrollbar-3dlight-color: ",'"'," + tdlightcolor + ",'"',";\\n",'"',"}\n")
document.write("if",open_c,"darkshadowcolor != ",'"',"",'"',")",open_cc,"csscontentpart += ",'"',"scrollbar-darkshadow-color: ",'"'," + darkshadowcolor + ",'"',";\\n",'"',"}\n")
document.write("if",open_c,"shadowcolor != ",'"',"",'"',")",open_cc,"csscontentpart += ",'"',"scrollbar-shadow-color: ",'"'," + shadowcolor + ",'"',";\\n",'"',"}\n")
document.write("if",open_c,"arrowcolor != ",'"',"",'"',")",open_cc,"csscontentpart += ",'"',"scrollbar-arrow-color: ",'"'," + arrowcolor + ",'"',";\\n",'"',"}\n")
document.write("if",open_c,"trackcolor != ",'"',"",'"',")",open_cc,"csscontentpart += ",'"',"scrollbar-track-color: ",'"'," + trackcolor + ",'"',";\\n",'"',"}\n")
document.write("\n")
document.write("\n")
document.write("cssstart = '",start,"STYLE type=",'"',"text",slash,"css",'"',">' + ",'"',"\\n",'"'," + ",'"',"",start,"!--",'"'," + ",'"',"\\n",'"'," + ",'"',"BODY ",open_cc,"",'"'," + ",'"',"\\n",'"',"\n")
document.write("cssend = ",'"',"}",'"'," + ",'"',"\\n",'"'," + ",'"',"-->",'"'," + ",'"',"\\n",'"'," + '",start,"",slash,"STYLE>' + ",'"',"\\n",'"',"\n")
document.write("\n")
document.write("document.barspecs.scrollcode.value = cssstart + csscontentpart + cssend\n")
document.write("\n")
document.write("\n")
document.write("}\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("",slash,"",slash,"-->\n")
document.write("",start,"",slash,"scr","ipt>\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("",start,"img height=",'"',"1",'"'," src=",'"',"http:",slash,"",slash,"www.disipal.net",slash,"images",slash,"11dot-s.gif",'"'," width=",'"',"500",'"'," border=",'"',"0",'"',">",start,"br>\n")
document.write("\n")
document.write("",start,"img border=",'"',"0",'"'," src=",'"',"http:",slash,"",slash,"www.disipal.net",slash,"images",slash,"11dot.gif",'"'," width=",'"',"5",'"'," height=",'"',"5",'"',">",start,"br>\n")
document.write("\n")
document.write("\n")
document.write("",start,"table border=",'"',"0",'"'," width=",'"',"500",'"'," cellspacing=",'"',"0",'"'," cellpadding=",'"',"10",'"',">\n")
document.write("",start,"tr>",start,"td width=",'"',"100%",'"',">\n")
document.write("\n")
document.write("",start,"font class=",'"',"NArial",'"',">\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("",start,"",slash,"font>\n")
document.write("\n")
document.write("",start,"",slash,"td>",start,"",slash,"tr>\n")
document.write("",start,"",slash,"table>\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("",start,"form name=",'"',"barspecs",'"',">\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("",start,"input type=",'"',"hidden",'"'," name=",'"',"navlinks",'"'," value=",'"',"",'"',">\n")
document.write("\n")
document.write("\n")
document.write("",start,"table border=",'"',"0",'"'," width=",'"',"500",'"'," cellspacing=",'"',"0",'"'," cellpadding=",'"',"0",'"'," bgcolor=",'"',"#39597D",'"',">\n")
document.write("  ",start,"tr>\n")
document.write("    ",start,"td width=",'"',"100%",'"'," bgcolor=",'"',"#808080",'"',">\n")
document.write("      ",start,"table border=",'"',"0",'"'," width=",'"',"100%",'"'," cellspacing=",'"',"0",'"'," cellpadding=",'"',"7",'"',">\n")
document.write("        ",start,"tr>\n")
document.write("          ",start,"td width=",'"',"100%",'"',">",start,"b>",start,"font class=",'"',"NArial",'"'," color=",'"',"#FFFFFF",'"',">Scrollbar\n")
document.write("            Properties",start,"",slash,"font>",start,"",slash,"b>",start,"",slash,"td>\n")
document.write("        ",start,"",slash,"tr>\n")
document.write("      ",start,"",slash,"table>\n")
document.write("      ",start,"table border=",'"',"0",'"'," width=",'"',"100%",'"'," cellspacing=",'"',"1",'"'," cellpadding=",'"',"0",'"',">\n")
document.write("        ",start,"tr>\n")
document.write("          ",start,"td width=",'"',"48%",'"'," bgcolor=",'"',"#FFFFFF",'"'," valign=",'"',"top",'"',">\n")
document.write("            ",start,"table border=",'"',"0",'"'," width=",'"',"100%",'"'," cellspacing=",'"',"3",'"'," cellpadding=",'"',"0",'"',">\n")
document.write("              ",start,"tr>\n")
document.write("                ",start,"td width=",'"',"100%",'"',">",start,"img border=",'"',"0",'"'," src=",'"',"http:",slash,"",slash,"www.disipal.net",slash,"images",slash,"scroll.gif",'"'," width=",'"',"232",'"'," height=",'"',"242",'"',">",start,"",slash,"td>\n")
document.write("              ",start,"",slash,"tr>\n")
document.write("            ",start,"",slash,"table>\n")
document.write("          ",start,"",slash,"td>\n")
document.write("          ",start,"td width=",'"',"52%",'"'," bgcolor=",'"',"#C0C0C0",'"',">\n")
document.write("            ",start,"table border=",'"',"0",'"'," width=",'"',"100%",'"'," cellspacing=",'"',"0",'"'," cellpadding=",'"',"4",'"',">\n")
document.write("              ",start,"tr>\n")
document.write("                ",start,"td width=",'"',"54%",'"'," align=",'"',"right",'"',">",start,"b>",start,"font class=",'"',"NArial",'"'," color=",'"',"#FFFFFF",'"',">face-color:",start,"",slash,"font>",start,"",slash,"b>",start,"",slash,"td>\n")
document.write("                ",start,"td width=",'"',"46%",'"',">",start,"input class=",'"',"hexfield",'"'," type=",'"',"text",'"'," name=",'"',"face",'"'," value=",'"',"",'"'," size=",'"',"10",'"',">",start,"",slash,"td>\n")
document.write("              ",start,"",slash,"tr>\n")
document.write("              ",start,"tr>\n")
document.write("                ",start,"td width=",'"',"54%",'"'," bgcolor=",'"',"#B4B4B4",'"'," align=",'"',"right",'"',">",start,"b>",start,"font class=",'"',"NArial",'"'," color=",'"',"#FFFFFF",'"',">highlight-color:",start,"",slash,"font>",start,"",slash,"b>",start,"",slash,"td>\n")
document.write("                ",start,"td width=",'"',"46%",'"'," bgcolor=",'"',"#B4B4B4",'"',">",start,"input class=",'"',"hexfield",'"'," type=",'"',"text",'"'," name=",'"',"highlight",'"'," value=",'"',"",'"'," size=",'"',"10",'"',">",start,"",slash,"td>\n")
document.write("              ",start,"",slash,"tr>\n")
document.write("              ",start,"tr>\n")
document.write("                ",start,"td width=",'"',"54%",'"'," align=",'"',"right",'"'," bgcolor=",'"',"#B4B4B4",'"',">",start,"b>",start,"font class=",'"',"NArial",'"'," color=",'"',"#FFFFFF",'"',">3dlight-color:",start,"",slash,"font>",start,"",slash,"b>",start,"",slash,"td>\n")
document.write("                ",start,"td width=",'"',"46%",'"'," bgcolor=",'"',"#B4B4B4",'"',">",start,"input class=",'"',"hexfield",'"'," type=",'"',"text",'"'," name=",'"',"tdlight",'"'," value=",'"',"",'"'," size=",'"',"10",'"',">",start,"",slash,"td>\n")
document.write("              ",start,"",slash,"tr>\n")
document.write("              ",start,"tr>\n")
document.write("                ",start,"td width=",'"',"54%",'"'," align=",'"',"right",'"',">",start,"b>",start,"font class=",'"',"NArial",'"'," color=",'"',"#FFFFFF",'"',">darkshadow-color:",start,"",slash,"font>",start,"",slash,"b>",start,"",slash,"td>\n")
document.write("                ",start,"td width=",'"',"46%",'"',">",start,"input class=",'"',"hexfield",'"'," type=",'"',"text",'"'," name=",'"',"darkshadow",'"'," value=",'"',"",'"'," size=",'"',"10",'"',">",start,"",slash,"td>\n")
document.write("              ",start,"",slash,"tr>\n")
document.write("              ",start,"tr>\n")
document.write("                ",start,"td width=",'"',"54%",'"'," align=",'"',"right",'"',">",start,"b>",start,"font class=",'"',"NArial",'"'," color=",'"',"#FFFFFF",'"',">shadow-color:",start,"",slash,"font>",start,"",slash,"b>",start,"",slash,"td>\n")
document.write("                ",start,"td width=",'"',"46%",'"',">",start,"input class=",'"',"hexfield",'"'," type=",'"',"text",'"'," name=",'"',"shadow",'"'," value=",'"',"",'"'," size=",'"',"10",'"',">",start,"",slash,"td>\n")
document.write("              ",start,"",slash,"tr>\n")
document.write("              ",start,"tr>\n")
document.write("                ",start,"td width=",'"',"54%",'"'," align=",'"',"right",'"'," bgcolor=",'"',"#B4B4B4",'"',">",start,"b>",start,"font class=",'"',"NArial",'"'," color=",'"',"#FFFFFF",'"',">arrow-color:",start,"",slash,"font>",start,"",slash,"b>",start,"",slash,"td>\n")
document.write("                ",start,"td width=",'"',"46%",'"'," bgcolor=",'"',"#B4B4B4",'"',">",start,"input class=",'"',"hexfield",'"'," type=",'"',"text",'"'," name=",'"',"arrow",'"'," value=",'"',"",'"'," size=",'"',"10",'"',">",start,"",slash,"td>\n")
document.write("              ",start,"",slash,"tr>\n")
document.write("              ",start,"tr>\n")
document.write("                ",start,"td width=",'"',"54%",'"'," align=",'"',"right",'"'," bgcolor=",'"',"#B4B4B4",'"',">",start,"b>",start,"font class=",'"',"NArial",'"'," color=",'"',"#FFFFFF",'"',">track-color:",start,"",slash,"font>",start,"",slash,"b>",start,"",slash,"td>\n")
document.write("                ",start,"td width=",'"',"46%",'"'," bgcolor=",'"',"#B4B4B4",'"',">",start,"input class=",'"',"hexfield",'"'," type=",'"',"text",'"'," name=",'"',"track",'"'," value=",'"',"",'"'," size=",'"',"10",'"',">",start,"",slash,"td>\n")
document.write("              ",start,"",slash,"tr>\n")
document.write("            ",start,"",slash,"table>\n")
document.write("          ",start,"",slash,"td>\n")
document.write("        ",start,"",slash,"tr>\n")
document.write("      ",start,"",slash,"table>\n")
document.write("    ",start,"",slash,"td>\n")
document.write("  ",start,"",slash,"tr>\n")
document.write("",start,"",slash,"table>\n")
document.write("\n")
document.write("\n")
document.write("",start,"table border=",'"',"0",'"'," width=",'"',"500",'"'," cellspacing=",'"',"0",'"'," cellpadding=",'"',"4",'"',">\n")
document.write("",start,"tr>",start,"td width=",'"',"249",'"'," align=",'"',"right",'"',">\n")
document.write("",start,"font class=",'"',"NArial",'"'," color=",'"',"#808080",'"',">",start,"b>Click here for a palette of Hex values -",start,"",slash,"b>",start,"",slash,"font>\n")
document.write("",start,"",slash,"td>",start,"td width=",'"',"231",'"'," align=",'"',"right",'"',">\n")
document.write("",start,"input type=",'"',"button",'"'," value=",'"',"Color Values",'"'," name=",'"',"makefield",'"'," class=",'"',"buttons",'"'," onclick=",'"',"launchhex",open_c,")",'"',">\n")
document.write("",start,"input type=",'"',"button",'"'," value=",'"',"Generate",'"'," class=",'"',"buttons",'"'," onclick=",'"',"generate",open_c,")",'"',">\n")
document.write("",start,"",slash,"td>",start,"",slash,"tr>",start,"",slash,"table>\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("",start,"table border=",'"',"0",'"'," width=",'"',"500",'"'," cellspacing=",'"',"0",'"'," cellpadding=",'"',"1",'"',">\n")
document.write("",start,"tr>",start,"td width=",'"',"100%",'"'," align=",'"',"center",'"'," bgcolor=",'"',"#808080",'"',">\n")
document.write("\n")
document.write("\n")
document.write("",start,"table border=",'"',"0",'"'," width=",'"',"100%",'"'," cellspacing=",'"',"0",'"'," cellpadding=",'"',"10",'"',">\n")
document.write("",start,"tr>",start,"td width=",'"',"100%",'"'," align=",'"',"center",'"'," bgcolor=",'"',"#C0C0C0",'"',">\n")
document.write("\n")
document.write("",start,"b>",start,"font class=",'"',"NArialW",'"',">Scrollbar CSS code:",start,"",slash,"font>",start,"",slash,"b>\n")
document.write("",start,"textarea rows=",'"',"10",'"'," name=",'"',"scrollcode",'"'," cols=",'"',"55",'"',">",start,"",slash,"textarea>\n")
document.write("\n")
document.write("",start,"",slash,"td>",start,"",slash,"tr>",start,"",slash,"table>\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("",start,"b>Scrollbar Generator Notes:",start,"",slash,"b>",start,"br>\n")
document.write("\n")
document.write("The scrollbar colors will only appear in IE5.5 or higher. They will have no effect in any other browser or browser version.",start,"br>\n")
document.write("",start,"img border=",'"',"0",'"'," src=",'"',"http:",slash,"",slash,"www.disipal.net",slash,"images",slash,"11dot.gif",'"'," width=",'"',"5",'"'," height=",'"',"8",'"',">",start,"br>\n")
document.write("You may choose not to enter a color value into a certain field. If you do, that element within the scrollbar will retain its default color.",start,"br>\n")
document.write("",start,"img border=",'"',"0",'"'," src=",'"',"http:",slash,"",slash,"www.disipal.net",slash,"images",slash,"11dot.gif",'"'," width=",'"',"5",'"'," height=",'"',"8",'"',">\n")
document.write("\n")
document.write("",start,"",slash,"td>",start,"",slash,"tr>",start,"",slash,"table>\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("",start,"",slash,"form>\n")
document.write("\n")
document.write("\n")
document.write("\n")
document.write("\n")
