<?php
define("_ADMINMENU","Administration");
define("_VIDEOADMIN","Video Admin");
define("_MANAGEVIDS","Manage Videos");
define("_ADDVIDS","Add Videos");
define("_ADDVID","Add Video");
define("_EDITVID","Edit Video");
define("_VIDADDED","Video Added");
define("_SETTINGSVIDS","Video Stream Settings");
define("_TITLE","Title");
define("_POSTEDON","Posted on");
define("_POSTEDBY","Posted by");
define("_VVIEW","View");
define("_VIEWS","Views");
define("_EDIT","Edit");
define("_DELETE","Delete");
define("_DELETEVID","Delete Video");
define("_PREVIOUS","Previous");
define("_NEXT","Next");
define("_NOVIDSINDB","You have not added any videos into the database yet.");
define("_DESCRIPTION","Description");
define("_VIDURL","Video URL");
define("_PPURL","Picture Preview URL");
define("_WIDTH","Width");
define("_HEIGHT","Height");
define("_PLUGIN","Plugin");
define("_WINDOWSMP","Windows Media Player");
define("_FLASHP","Flash Player");
define("_QUICKTIMEP","Quicktime Player");
define("_REALP","Real Player");
define("_REQUIRED","Required Fields");
define("_PAGE","Page");
define("_DELETEVIDCOMFIRM","You are about to delete this video. Are you sure?");
define("_YES","Yes");
define("_NO","No");
define("_VIDDELETED","Video deleted");
define("_BACK","back");
define("_NONE","None");
define("_CATEGORY","Category");
define("_ENTDELETED","Entry deleted");
define("_ENTRYCOMFIRM","You are about to delete all entries for this video. Are you sure?");
define("_REPORTEDBROKE","Videos reported as not working");
define("_VIDNAME","Video Name");
define("_USERNAME","Username");
define("_EMAIL","Email");
define("_DELETEENT","Delete all entries for this Video");
define("_GO","Go");
define("_GOBACKVID","Go back to Video Stream's main admin area?");
define("_NOBROKEN","No videos have been reported as broken");
define("_ENABLE","Enable");
define("_DISABLE","Disable");
define("_EVERYONE","Everyone");
define("_NOONE","No one");
define("_VISONLY","Visitors only");
define("_REGMEMBERSONLY","Registered Members Only");
define("_COMMENTPOSTING","Comment Posting");
define("_SENDTOFRIEND","Send to Friend");
define("_BROKENVIDS","Broken Videos");
define("_SUBMITVIDS","Submit Videos");
define("_RATING","Rating");
define("_ALLOWEDVIEW","Users allowed to view videos");
define("_SAVESETTINGS","Save Settings");
define("_USERSCOMMENT","Users allowed to comment on videos");
define("_USEREMAIL","Users allowed to send video link in emails");
define("_USERBROKEN","Users allowed to report videos broken");
define("_USERSUBMIT","Users allowed to submit videos");
define("_USERMODERATE","Users that need videos to be checked before submitting into main collection");
define("_USERRATE","Users allowed to rate videos");
define("_REQUESTSVIDS","Requested Videos");
define("_CATCOMFIRM","You are about to delete this category. Are you sure?");
define("_DELCAT","Delete Category");
define("_CATNAME","Category name");
define("_CATIMAGE","Category image url");
define("_ADDCAT","Add Category");
define("_ACCEPT","Accept");
define("_REJECT","Reject");
define("_NOVIDSRE","No videos have been requested.");
define("_REQUESTA","Request Accepted");
define("_REQUESTD","Request Deleted");
define("_AREQUEST","Accept Request");
define("_DREQUEST","Delete Request");
define("_AREQUESTCOM","You are about to accept this request. Are you sure?");
define("_DREQUESTCOM","You are about to delete this request. Are you sure?");
// NEW TO V4.1
define("_VIDSPERPAGE","Videos per Page");
define("_CHANGE","Change");
define("_EMBEDVIDURL","Video URL or &lt;embed&gt; code");
define("_CUSTOMEMBED","Custom &lt;embed&gt; Code");
// NEW TO V4.2
define("_DELETEENTRY","Delete Entry");
define("_PERMISSIONVIDS","Permission Settings");
define("_MANAGECATEGORIES","Manage Categories");
define("_PICTHUMB","Picture Thumbnail");
define("_COMFIRMCATDELETE","Are you sure you want to delete this category. Any videos under this category will be placed in the default category");
define("_DELCATNOTPARENT","This category is a parent category, please delete a non parent category first");
define("_ERROR","ERROR!");
define("_ADDMAINCAT","Add main category");
define("_ADDSUBCAT","Add sub-category");
define("_VS_IN","in");
define("_VS_AVCONTROL","Avatar Control");
define("_AVMAXWITHIE","Max avatar width/height");
define("_POINTSSYS","Points System");
define("_VS_NAME","Name");
define("_VS_POINTS","Points");
define("_COMMENTPOINT","Comment");
define("_POINTSFORVIEW","Points awarded each time a user views a video");
define("_POINTSFORCOMMENT","Points awarded each time a user comments on a video");
define("_POINTSFORSENDTOFRIEND","Points awarded each time a user sends a video link to a friend");
define("_POINTSFORSUBMITVIDEO","Points awarded each time a user submits a video to be added to the collection");
define("_POINTSFORRATEVIDEO","Points awarded each time a user rates a video");
// NEW to 4.5
define("_YOUTUBEVP", "YouTube Player");
define("_GOOGLEVP", "Google Video Player");
define("_CATCANBEVIEWEDBY", "Category can be viewed by");
define("_REQUIREUSERTOACCEPT", "Require user to accept disclaimer");
define("_EDITCAT", "Edit Category");
define("_DOWNLOADLINK", "Download Link");
define("_UADOWNLOADLINK", "Users allowed to see the download link");
define("_EMBEDEDHTML", "Embeded HTML");
define("_UAEMBEDEDHTML", "Users allowed to see the embeded HTML");
define("_WINAMP", "Winamp");
define("_FLVPLAYER", "FLV Player");
?>