<?php

$urlin = array(
"'(?<!/)modules.php\?name=Downloads&amp;d_op=ns_getit&amp;cid=([0-9]*)&amp;lid=([0-9]*)&amp;type=url([a-zA-Z#]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=ns_dl_auth_full_list&amp;author=([a-zA-Z0-9_-]*)#auth'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=ns_dl_rec_dl&amp;cid=([0-9]*)&amp;lid=([0-9]*)&amp;ttitle=([/:\-\'{}()\,\._&amp;a-zA-Z0-9+= ]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=ns_dl_send_rec'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=ns_dl_get_mirror_two&amp;lid=([0-9]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=ns_dl_get_mirror_one&amp;lid=([0-9]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=viewdownloaddetails&amp;cid=([0-9]*)&amp;lid=([0-9]*)&amp;ttitle=([/:\-\'{}()\,\._&amp;a-zA-Z0-9+= ]*)([a-zA-Z#]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=viewdownloadcomments&amp;cid=([0-9]*)&amp;lid=([0-9]*)&amp;ttitle=([/:\-\'{}()\,\._&amp;a-zA-Z0-9+= ]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=modifydownloadrequest&amp;lid=([0-9]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=brokendownload&amp;lid=([0-9]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=NewDownloads&amp;newdownloadshowdays=([0-9]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=NewDownloadsDate&amp;selectdate=([a-zA-Z0-9+]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=getit&amp;lid=([0-9]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=ratedownload&amp;cid=([0-9]*)&amp;lid=([0-9]*)&amp;ttitle=([/:\-\'{}()\,\._&amp;a-zA-Z0-9+= ]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=ratedownload&amp;lid=([0-9]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=(TopRated|MostPopular)&amp;ratenum=([0-9]*)&amp;ratetype=(num|percent)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=(AddDownload|NewDownloads|MostPopular|TopRated)#(adddownload|newdownloads|mostpop|toprated)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=viewdownload&amp;cid=([0-9]*)&amp;orderby=([a-zA-Z0-9+]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=viewdownload&amp;cid=([0-9]*)&amp;min=([0-9]*)&amp;orderby=([a-zA-Z0-9+]*)&amp;show=([0-9]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=search&amp;query=([/:\-\'{}()\,\._&amp;a-zA-Z0-9+= ]*)&amp;min=([0-9]*)&amp;orderby=([a-zA-Z0-9+]*)&amp;show=([0-9]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=search&amp;query=([/:\-\'{}()\,\._&amp;a-zA-Z0-9+= ]*)&amp;orderby=([a-zA-Z0-9+]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=search'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=outsidedownloadsetup&amp;lid=([0-9]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=viewdownload&cid=1#cat'",
"'(?<!/)modules.php\?name=Downloads&amp;file=ns_uploads_file&amp;type=file'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=gfx&amp;random_num=([a-zA-Z0-9]*)'",
"'(?<!/)modules.php\?name=Downloads&amp;d_op=ns_pass_help&amp;thepass=([a-zA-Z0-9]*)'",
"'(?<!/)modules.php\?name=Downloads'"
);

$urlout = array(
"download-get-\\1-\\2.html",
"download-show-detailedlist-\\1.html",
"downloadrecommend-\\1-\\2-\\3.html",
"download-send.html",
"download-file-mirrortwo\\1.html",
"download-file-mirrorone\\1.html",
"downloaddetails-\\1-\\2-\\3.html",
"downloadcomments-\\1-\\2-\\3.html",
"download-mod-\\1.html",
"download-broken-\\1.html",
"download-shownew-\\1.html",
"download-seldate-\\1.html",
"download-file-\\1.html",
"ratedownload-\\1-\\2-\\3.html",
"ratedownload-\\1.html",
"download-\\1-\\2-\\3.html",
"downloads-\\1.html",
"download\\1-orderby\\2.html",
"download\\1-\\2-\\3-\\4.html",
"download-search-\\1-\\2-\\3-\\4.html",
"download-search-\\1-\\2.html",
"download-search.html",
"download-outside-\\1.html",
"downloads-cat\\1.html",
"download-upload.html",
"downloads-gfx-\\1.html",
"downloads-help-\\1.html",
"downloads.html"
);

?>
